app:
  build: platra/ 
  command: rails server -p 3000 -b '0.0.0.0'
  links:
    - db
  volumes:
    - platra/:/app
  ports:
    - "3000:3000"

db:
  image: mariadb
  environment:
    MYSQL_USERNAME: root 
    MYSQL_ROOT_PASSWORD: root 

phpmyadmin:
  image: phpmyadmin/phpmyadmin 
  links:
      - db
  ports:
    - 8181:80
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: root 
